// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:desea_mvp/data/models/carta_guardada_model.dart';
import 'package:desea_mvp/data/models/carta_model.dart';
import 'package:desea_mvp/data/models/carta_personalizada_model.dart';
import 'package:desea_mvp/data/models/mazo_model.dart';
import 'package:desea_mvp/data/models/perfil_model.dart';
import 'package:desea_mvp/data/models/sesion_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CartaGuardadaModelAdapter());
    registerAdapter(CartaModelAdapter());
    registerAdapter(CartaPersonalizadaModelAdapter());
    registerAdapter(MazoModelAdapter());
    registerAdapter(PerfilModelAdapter());
    registerAdapter(SesionModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CartaGuardadaModelAdapter());
    registerAdapter(CartaModelAdapter());
    registerAdapter(CartaPersonalizadaModelAdapter());
    registerAdapter(MazoModelAdapter());
    registerAdapter(PerfilModelAdapter());
    registerAdapter(SesionModelAdapter());
  }
}
